#!/usr/bin/env python3
"""
phylo_utils.py
--------------
Phylogenetics utility functions for the GPCR B1-family pipeline.

Provides helpers for:
  - Reading and writing FASTA files
  - Sanitising sequence labels
  - Parsing Newick tree strings
  - Grouping sequences by their GPCR super-family

These are pure, testable functions extracted from build_phylogeny.py and
render_tree_pdf.py to improve code reuse and testability.

Example::

    from phylo_utils import read_fasta, group_labels_by_family, sanitize_label

    records = read_fasta("sequences.fasta")
    family_map = group_labels_by_family(records)
    safe = sanitize_label("Takifugu rubripes")
"""

import re
from typing import Iterator


# ---------------------------------------------------------------------------
# FASTA I/O
# ---------------------------------------------------------------------------

def read_fasta(path: str) -> list[tuple[str, str]]:
    """Parse a multi-FASTA file and return (header, sequence) tuples.

    Sequences are concatenated across multiple lines. Headers have the leading
    ``>`` stripped.

    Parameters
    ----------
    path:
        Path to the FASTA file.

    Returns
    -------
    list[tuple[str, str]]
        List of (header, sequence) pairs in file order.
    """
    records: list[tuple[str, str]] = []
    header: str | None = None
    seq_parts: list[str] = []

    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip()
            if line.startswith(">"):
                if header is not None:
                    records.append((header, "".join(seq_parts)))
                header = line[1:]
                seq_parts = []
            elif line:
                seq_parts.append(line)

    if header is not None:
        records.append((header, "".join(seq_parts)))

    return records


def write_fasta(records: list[tuple[str, str]], path: str) -> None:
    """Write *records* as a multi-FASTA file to *path*.

    Parameters
    ----------
    records:
        Iterable of (header, sequence) pairs.
    path:
        Output file path (will be overwritten if it exists).
    """
    with open(path, "w", encoding="utf-8") as fh:
        for header, seq in records:
            fh.write(f">{header}\n{seq}\n")


def iter_fasta(path: str) -> Iterator[tuple[str, str]]:
    """Lazily yield (header, sequence) tuples from a FASTA file.

    Suitable for large files where loading everything into memory is undesirable.
    """
    header: str | None = None
    seq_parts: list[str] = []

    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip()
            if line.startswith(">"):
                if header is not None:
                    yield header, "".join(seq_parts)
                header = line[1:]
                seq_parts = []
            elif line:
                seq_parts.append(line)

    if header is not None:
        yield header, "".join(seq_parts)


# ---------------------------------------------------------------------------
# Label utilities
# ---------------------------------------------------------------------------

_UNSAFE_LABEL_RE = re.compile(r"[^A-Za-z0-9_]+")


def sanitize_label(value: str, max_length: int = 120) -> str:
    """Return a FASTA/Newick-safe label derived from *value*.

    Replaces non-alphanumeric characters with underscores, strips leading/
    trailing underscores, and truncates to *max_length* characters.

    Parameters
    ----------
    value:
        Raw label string (e.g. species name or description).
    max_length:
        Maximum allowed label length (default: 120).

    Returns
    -------
    str
        Sanitised label, or ``"seq"`` if the result is empty.
    """
    safe = _UNSAFE_LABEL_RE.sub("_", value).strip("_")
    safe = safe[:max_length]
    return safe or "seq"


def parse_label_parts(label: str) -> dict[str, str]:
    """Split a pipeline FASTA label into its component fields.

    Pipeline labels have the form::

        {species}_{accession}_{family}_{subfamily}

    Parameters
    ----------
    label:
        A label generated by the pipeline's ``build_phylogeny.py``.

    Returns
    -------
    dict
        Keys: ``species``, ``accession``, ``family``, ``subfamily``.
        Values are ``"?"`` for fields that cannot be parsed.
    """
    parts = label.split("_", 3)
    keys = ["species", "accession", "family", "subfamily"]
    return {k: parts[i] if i < len(parts) else "?" for i, k in enumerate(keys)}


# ---------------------------------------------------------------------------
# Grouping helpers
# ---------------------------------------------------------------------------

def group_labels_by_family(
    records: list[tuple[str, str]],
) -> dict[str, list[str]]:
    """Return a mapping from family name to list of sequence labels.

    Extracts the family field from each pipeline-style FASTA label (field 3,
    0-indexed).  Labels that cannot be parsed are placed under ``"UNKNOWN"``.

    Parameters
    ----------
    records:
        List of (label, sequence) tuples as returned by :func:`read_fasta`.

    Returns
    -------
    dict[str, list[str]]
        ``{family: [label, …]}``
    """
    groups: dict[str, list[str]] = {}
    for label, _ in records:
        parts = parse_label_parts(label)
        family = parts.get("family") or "UNKNOWN"
        groups.setdefault(family, []).append(label)
    return groups


def count_sequences_per_family(records: list[tuple[str, str]]) -> dict[str, int]:
    """Return a count of sequences per GPCR family in *records*.

    Parameters
    ----------
    records:
        List of (label, sequence) tuples.

    Returns
    -------
    dict[str, int]
        ``{family: count}``
    """
    groups = group_labels_by_family(records)
    return {family: len(labels) for family, labels in sorted(groups.items())}


# ---------------------------------------------------------------------------
# Sequence statistics
# ---------------------------------------------------------------------------

def sequence_length_stats(records: list[tuple[str, str]]) -> dict[str, float]:
    """Return basic length statistics for sequences in *records*.

    Returns
    -------
    dict
        Keys: ``count``, ``min``, ``max``, ``mean``.
    """
    if not records:
        return {"count": 0, "min": 0.0, "max": 0.0, "mean": 0.0}
    lengths = [len(seq) for _, seq in records]
    return {
        "count": len(lengths),
        "min": float(min(lengths)),
        "max": float(max(lengths)),
        "mean": sum(lengths) / len(lengths),
    }
